# Generated by Django 5.2 on 2025-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
