# Generated by Django 5.2 on 2025-04-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default="fallback.jpg", upload_to=""),
        ),
    ]
